import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'


const roobert = localFont({
  src: '../fonts/RoobertTRIALVF-BF67243fd545701.ttf',
  variable: '--font-roobert',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roobert.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
